### PR TITLE
TypeExtension.IsStatic name fix + Test Name Assertions

### PR DESCRIPTION
**Pull request by mbaker3**
- `TypeExtension.IsStatic` did not have the correct name casing
- Add test method name assertions to make sure test names are kept inline with method names if they get refactored.

### What is the current behaviour?
- `TypeExtension.isStatic` is not the correct naming convention
- Refactored methods that have unit tests may not have their test names updated. 

### What is the new behaviour?
- `TypeExtension.IsStatic`...promoted that `I`
- New assertions ensure that tests fail if a test's method name isn't updated to reflect the name of the method it is testing.

### What issues does this resolve?
None

### What PRs does this depend on?
 - #136 

### Does this introduce a breaking change?
 - [x] Yes - Any calls to `isStatic` should be changed to `IsStatic`
 - [ ] No

### CODE REVIEW

**Comment by tjvezina** [comment]
I'm not a fan of requiring all tests to start with an assert for the test name, and the format is going to change with #132 anyway. I see the benefit of automatic refactor handling, but I'm not sure the overhead is worth it - if you rename a function that's used in a unit test, you'll have to commit the changes to said test anyway, and will hopefully know (or the PR reviewer will notice) that the test name must be updated too.

At the very least, should it be `Does.Equal($"{nameof(SomeFunction)}Test")` instead of `StartsWith`, in case your refactoring involves simply shortening a function name? (Ex. `GetXValue` -> `GetX` would still match `GetXValueTest`)

**Comment by mbaker3** [comment]
> ...the format is going to change with https://github.com/decline-cookies/anvil-csharp-core/issues/132

Ah right I forgot about that issue. The rules can be adjusted as part of that change but I think it's still possible to assert against the relevant names (maybe even easier?).

>  I see the benefit of automatic refactor handling, but I'm not sure the overhead is worth it - if you rename a function that's used in a unit test, you'll have to commit the changes to said test anyway, and will hopefully know (or the PR reviewer will notice) that the test name must be updated too.

I think the fewer things we have to remember as reviewers the better. It's so easy to miss something like that when looking at diffs. It's low effort to implement and provided me enough value during development to want to apply this convention to all tests.

@jkeon want to break a tie?

> At the very least, should it be Does.Equal($"{nameof(SomeFunction)}Test") instead of StartsWith, in case your refactoring involves simply shortening a function name? (Ex. GetXValue -> GetX would still match GetXValueTest)

The check is never going to be perfect although the test refactoring work may make this a more reliable check in the future. I can include the `...Test` portion to make it a better check for now.

**Comment by jkeon** [comment]
> want to break a tie?

This is for whether the Test function name matches the function it's testing? The extra boiler plate is a little annoying, but I can see the benefit for keeping things nice and organized. 

It's not really part of the test though so I wonder if it would be better to have it as an Attribute? 

```csharp
[Test, Order(0)]
//Probably needs a better name for the attribute
[AnvilTestNamingConsistency(nameof(Array2DExtension.Populate)]
 public static void PopulateTest()
{
    etc
```

Code in the `PopulateTest` is solely for the test. As part of the `Setup` phase, you run a pass to gather all the methods with this attribute and then compare them to make sure they match the format?

I realize this is more work and could be a separate issue but I think the spirit is correct?



I would agree that we would want to check equality with the method names rather than StartsWith since we should know exactly what the method name should be.

**Comment by mbaker3** [comment]
> This is for whether the Test function name matches the function it's testing? 

Whether we should have the assert at all I think was the main challenge. It seems like everyone identifies at least SOME benefit and then there's some question around whether it's worth it and how we go about it.

Given the discussion I'll adjust the name assertions to be a little more resilient to edge case name changes (Ex: `GetXValue` -> `GetX`).

If someone wants to think through a different approach (attributes, etc..) to propose in an issue they can. For now it's a low effort, best chance approach.

---

> It's not really part of the test though so I wonder if it would be better to have it as an Attribute?

I don't know. I'm not really bothered by the extra test. I agree that it is a bit of a tangent from the goal of the test method but I really can't see myself ever thinking it's worth the time to build out this feature.

> I would agree that we would want to check equality with the method names rather than StartsWith since we should know exactly what the method name should be.

This isn't necessarily true. There are unit tests that group the testing of multiple methods together. It's not the "right" way to test but sometimes it's just not practical.
Example: https://github.com/decline-cookies/anvil-unity-dots/blob/765b267e04e427b069e400fe7c3381b194356054/Scripts/Editor/Tests/Mathematics/MathExtensionTests.cs#L26

**Comment by mbaker3** [comment]
Test name assertions adjusted and I did catch one test that wasn't correctly named.
In most cases it's not an exact `Is.EqualTo` check.

I've made exceptions and kept the `StartWith` but added a `"Test"` suffix to the name for situations where there are many tests for one util method.

The upside to this updated approach is that the test is more resilient against name refactoring.
The downside is that there's some manual work required if you want to change the method name for a test. That's not a big deal though since you're already be in there making edits.

**Review by jkeon — APPROVED** [review]

**Review by tjvezina — APPROVED** [review]
> There are unit tests that group the testing of multiple methods together.

I debated bringing this up - I agree that unit tests typically map to a single function but not always, yet that also goes against the planned reorganizing in #132, which explicitly groups tests by function.

For now at least, I'm fine with these changes, perhaps only because I hope to find an alternative whenever I get around to #132. I feel like as-is, it will be too easy in the future to add some unit tests and forget to include this `Assert` for the function name itself, but we'll see.

**Comment by mbaker3** [comment]
> I debated bringing this up - I agree that unit tests typically map to a single function but not always, yet that also goes against the planned reorganizing in https://github.com/decline-cookies/anvil-csharp-core/issues/132, which explicitly groups tests by function.

Yea, I mean I could copy/paste the same tests into two different methods but that doesn't feel like a great solution. It's tough to test some of these methods in a vacuum. 

> I feel like as-is, it will be too easy in the future to add some unit tests and forget to include this Assert for the function name itself, but we'll see.

Agreed, a more automated approach would be best.

**Pull request merged**
